name: Publish on GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwayland-dev wayland-protocols libxkbcommon-dev libx11-dev libxcursor-dev libxi-dev

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Setup Zig Compiler
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0

      - name: Compile Live Timeline for wasm32-emscripten
        run: |
          cd live_timeline
          zig build -Dtarget=wasm32-emscripten
          rm zig-out/htmlout/index.html
          mv zig-out/htmlout/* ../src/assets/static
          cd ..

      - name: Setup Deno environment
        uses: denoland/setup-deno@v2

      - name: Build site
        run: deno task build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
